### ISSUE TITLE
Retrying to make a payment after unsuccesful attempt cause crash in TokenizableCardPaymentFormFragment

### ISSUE THREAD

**Issue by tneagu** [hipay/hipay-fullservice-sdk-android#65]
After one unsuccesful payment with a Visa card, when I try to pay again I get a NullPointerException in TokenizableCardPaymentFormFragment at line 777: 
`CheckoutData.checkoutData.setPaymentMethod(paymentProduct.getCode());`

I am using version 1.5.1. Can you please help? The stack trace is: 

`java.lang.NullPointerException: Attempt to invoke virtual method 'void com.hipay.fullservice.core.monitoring.CheckoutData.setPaymentMethod(java.lang.String)' on a null object reference
        at com.hipay.fullservice.screen.fragment.TokenizableCardPaymentFormFragment$6.onSuccess(TokenizableCardPaymentFormFragment.java:777)
        at com.hipay.fullservice.core.client.interfaces.SecureVaultReqHandler.onSuccess(SecureVaultReqHandler.java:31)
        at com.hipay.fullservice.core.client.interfaces.AbstractReqHandler.handleCallback(AbstractReqHandler.java:205)
        at com.hipay.fullservice.core.client.AbstractClient.onLoadFinished(AbstractClient.java:244)
        at com.hipay.fullservice.core.client.AbstractClient.onLoadFinished(AbstractClient.java:42)
        at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
        at androidx.loader.content.Loader.deliverResult(Loader.java:132)
        at com.hipay.fullservice.core.network.AbstractHttpClient.deliverResult(AbstractHttpClient.java:97)
        at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
        at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
        at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by jprotin** [comment]
Hi @tneagu 

Thank you for your issue. We are testing to reproduce the bug and we fix quickly.

Best.

**Comment by jprotin** [comment]
Hi @tneagu 

You can test with the new release : https://github.com/hipay/hipay-fullservice-sdk-android/releases/tag/1.5.2

**Comment by tneagu** [comment]
Ok, thank you for the quick fix & release
